export const GET_CUSTOMER_SUCCESS="GET_CUSTOMER_SUCCESS"
export const GET_CUSTOMER_PENDING="GET_CUSTOMER_PENDING"
export const GET_CUSTOMER_FAILURE="GET_CUSTOMER_FAILURE"

export const POST_CUSTOMER_SUCCESS="POST_CUSTOMER_SUCCESS"
export const POST_CUSTOMER_PENDING="POST_CUSTOMER_PENDING"
export const POST_CUSTOMER_FAILURE="POST_CUSTOMER_FAILURE"


export const DELETE_CUSTOMER_SUCCESS="DELETE_CUSTOMER_SUCCESS"
export const DELETE_CUSTOMER_PENDING="DELETE_CUSTOMER_PENDING"
export const DELETE_CUSTOMER_FAILURE="DELETE_CUSTOMER_FAILURE"


export const GET_SUPPLIER_SUCCESS="GET_SUPPLIER_SUCCESS"
export const POST_SUPPLIER_SUCCESS="POST_SUPPLIER_SUCCESS"
export const DELETE_SUPPLIER_SUCCESS="DELETE_SUPPLIER_SUCCESS"